# Generated by Django 4.0.4 on 2022-04-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='engine_power',
            field=models.IntegerField(verbose_name='Мощность, л/с'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Изменить фото'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='type_of_engine',
            field=models.CharField(choices=[(None, 'Выберите тип двигателя'), ('petrol', 'Бензиновый'), ('diesel', 'Дизельный')], db_index=True, max_length=50, verbose_name='Двигатель'),
        ),
    ]
