# Generated by Django 4.0.4 on 2022-05-03 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0004_alter_cars_engine_power_alter_cars_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AddConstraint(
            model_name='cars',
            constraint=models.CheckConstraint(check=models.Q(('year__gte', 1900), ('year__lte', 3000)), name='cars_cars_year_constraint'),
        ),
        migrations.AddConstraint(
            model_name='cars',
            constraint=models.CheckConstraint(check=models.Q(('engine_capacity__gt', 0), ('engine_capacity__lt', 15)), name='cars_cars_engine_capacity_constraint'),
        ),
        migrations.AddField(
            model_name='avguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
