# Generated by Django 4.0.4 on 2022-05-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_avguser_alter_cars_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
    ]
