# Generated by Django 4.0.4 on 2022-05-03 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_brands_slug_alter_cars_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3000)], verbose_name='Год выпуска'),
        ),
    ]
