# Generated by Django 4.0.4 on 2022-05-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_cars_slug_alter_cars_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='pre_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
