# Generated by Django 4.0.4 on 2022-05-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_cars_pre_slug_alter_cars_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='pre_slug',
        ),
    ]
