# Generated by Django 4.0.4 on 2022-05-08 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_comments_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='engine_capacity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска'),
        ),
    ]
