# Generated by Django 4.0.4 on 2022-05-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_comments_car_alter_comments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-create_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='comments',
            order_with_respect_to=None,
        ),
    ]
